# Generated by Django 5.2.7 on 2025-10-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_alter_pin_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='account_name',
            new_name='cashapp',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='account_number',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='bank',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='transfer',
            name='gateway',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='paypal_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='swift_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='wallet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='wise_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
