# Generated by Django 5.2.7 on 2025-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_alter_transfer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='account_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='bank_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
