# Generated by Django 5.2.7 on 2025-10-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_transfer_account_number_transfer_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50, null=True),
        ),
    ]
